### PR TITLE
Bugfix for SuReal, Microplanning

### LINKED ISSUE #3544: MicroplanningUTest and SuRealUTest fail
From the test log, looks like SuReal fails to even generate a very simple sentence, and it fails when it's trying to match the disjuncts between two words, e.g. he <-> she, runs <-> eats as in the first test, which is very strange... and it has started failing when I switch to using Link Grammar 5.6.1.

@linas is there any change in 5.6.1 that may give words a different set of disjuncts or something like that?

BTW since the Microplanner uses SuReal, I believe fixing SuRealUTest will also "fix" the MicroplanningUTest.

### PR DESCRIPTION
**Pull request by linas**
It appars that the loop to read LG expressions was over-complex.
With this change, SuReal and MicroPlanning pass for LG version 5.6.1
I did not test earlier versions of LG.

Fixes #3544

### CODE REVIEW

**Comment by linas** [comment]
@stellarspot could you test this with earlier versions of LG? I'm 99% certain that this should work, but cannot say for certain.

**Comment by linas** [comment]
ah, what the heck. all unit tests passed.  I'm merging. If something fancier is needed for older LG versions, then ... a distinct patch is needed.

**Comment by stellarspot** [comment]
Tests MicroplanningUTest and SuRealUTest pass with LinkGrammar 5.6.0 and 5.6.2.

With LinkGrammar 5.5.1 SuRealUTest fails with error described in #3551
`../../../opencog/nlp/lg-dict/liblg-dict-entry.so: undefined reference to 'boolean_dictionary_lookup'`

**Comment by linas** [comment]
> 'boolean_dictionary_lookup'

Yeah, that's a screw-up. It was a public API function that was missing a declaration to export it to the shlib.  For some (unkonw-to-me) reason, my system doesn't trip on this, but others do.
