### ISSUE TITLE
moses compile issue

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#1228]
moses exracted with extraction script won't compile on my new ubuntu 14.04 installation.  i had to manually add jaccard_index.h and geometric_mean_mirror.h to the extracted files but then it snaged on the following that wasn't obviously a missing header file.  i havne't checked the dependencies against the automatic dependency installer script but nothing immediately obvious is missing, and c++ is all ahmaric to me:

make -j4

[ 62%] Building CXX object moses3/learning/moses/CMakeFiles/moses.dir/deme/feature_selector.cc.o
/home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/learning/moses/deme/feature_selector.cc: In member function ‘void moses3::moses::feature_selector::log_stats_top_feature_sets(const feature_set_pop&) const’:
/home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/learning/moses/deme/feature_selector.cc:270:56: error: ‘jaccardIndex’ was not declared in this scope
                 jaccardIndex(i_it->second, j_it->second)
                                                        ^
/home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/learning/moses/deme/feature_selector.cc:270:56: note: suggested alternative:
In file included from /home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/learning/moses/deme/feature_selector.cc:36:0:
/home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/util/jaccard_index.h:33:7: note:   ‘opencog::jaccardIndex’
 float jaccardIndex(const Set& s1, const Set& s2) {
       ^
/home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/learning/moses/deme/feature_selector.cc: In lambda function:
/home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/learning/moses/deme/feature_selector.cc:382:68: error: ‘jaccardIndex’ was not declared in this scope
                     jaccardIndex(last_fs_cit->second, csc_fs.second)
                                                                    ^
/home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/learning/moses/deme/feature_selector.cc:382:68: note: suggested alternative:
In file included from /home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/learning/moses/deme/feature_selector.cc:36:0:
/home/biocog/opencog/scripts/learning/moses/extract_moses/moses/1.17.15/moses3/util/jaccard_index.h:33:7: note:   ‘opencog::jaccardIndex’
 float jaccardIndex(const Set& s1, const Set& s2) {
       ^
[ 63%] Building CXX object moses3/learning/moses/CMakeFiles/moses.dir/eda/initialization.cc.o
make[2]: *** [moses3/learning/moses/CMakeFiles/moses.dir/deme/feature_selector.cc.o] Error 1

**Comment by ngeiswei** [comment]
Thanks for the report. Fixed in commit https://github.com/opencog/opencog/commit/b4d92441b1db6f63d049b2dfb9575c056761317a
