### ISSUE TITLE
OpenCog failed to build with boost 1.58.0

### ISSUE THREAD

**Issue by SamuelHassine** [opencog/opencog#2331]
Hi there,

OpenCog does not compile on Ubuntu 16.04 (boost 1.58.0), here it is the error:

`[ 68%] Building CXX object opencog/spatial/CMakeFiles/SpaceMap.dir/Entity.cc.o
In file included from /usr/include/boost/variant/get.hpp:24:0,
                 from /home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:28:
/usr/include/boost/variant/detail/element_index.hpp:38:69: error: ‘remove_cv’ in namespace ‘boost’ does not name a template type
             variant_element_functor<boost::mpl::_1, typename boost::remove_cv<T>::type >
                                                                     ^
/usr/include/boost/variant/detail/element_index.hpp:38:78: error: expected template-argument before ‘<’ token
             variant_element_functor<boost::mpl::_1, typename boost::remove_cv<T>::type >
                                                                              ^
/usr/include/boost/variant/detail/element_index.hpp:38:78: error: expected ‘>’ before ‘<’ token
/usr/include/boost/variant/detail/element_index.hpp:38:88: error: template argument 2 is invalid
             variant_element_functor<boost::mpl::_1, typename boost::remove_cv<T>::type >
                                                                                        ^
/usr/include/boost/variant/detail/element_index.hpp:39:9: error: expected ‘::’ before ‘>’ token
         >
         ^
/usr/include/boost/variant/detail/element_index.hpp:39:9: error: expected identifier before ‘>’ token
/usr/include/boost/variant/detail/element_index.hpp:39:9: error: template argument 2 is invalid
/usr/include/boost/variant/detail/element_index.hpp:40:5: error: expected ‘::’ before ‘>’ token
     >
     ^
/usr/include/boost/variant/detail/element_index.hpp:40:5: error: expected identifier before ‘>’ token
/usr/include/boost/variant/detail/element_index.hpp:40:5: error: template argument 2 is invalid
/usr/include/boost/variant/detail/element_index.hpp:41:1: error: expected ‘::’ before ‘{’ token
 {};
 ^
/usr/include/boost/variant/detail/element_index.hpp:41:1: error: expected class-name before ‘{’ token
/usr/include/boost/variant/detail/element_index.hpp: In instantiation of ‘struct boost::detail::variant::holds_element<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const bool>’:
/usr/include/boost/variant/get.hpp:201:35:   required from ‘typename boost::add_pointer<const U>::type boost::strict_get(const boost::variant<T0, TN ...>*) [with U = bool; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const bool*]’
/usr/include/boost/variant/get.hpp:269:25:   required from ‘typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, TN ...>*) [with U = bool; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const bool*]’
/home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:281:84:   required from here
/usr/include/boost/variant/detail/element_index.hpp:49:8: error: no type named ‘type’ in ‘struct boost::detail::variant::element_iterator<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const bool>’
 struct holds_element :
        ^
In file included from /home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:28:0:
/usr/include/boost/variant/get.hpp: In instantiation of ‘typename boost::add_pointer<const U>::type boost::strict_get(const boost::variant<T0, TN ...>*) [with U = bool; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const bool*]’:
/usr/include/boost/variant/get.hpp:269:25:   required from ‘typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, TN ...>*) [with U = bool; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const bool*]’
/home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:281:84:   required from here
/usr/include/boost/variant/get.hpp:201:35: error: ‘value’ is not a member of ‘boost::detail::variant::holds_element<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const bool>’
     return relaxed_get<U>(operand);
                                   ^
In file included from /usr/include/boost/variant/get.hpp:24:0,
                 from /home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:28:
/usr/include/boost/variant/detail/element_index.hpp: In instantiation of ‘struct boost::detail::variant::holds_element<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const std::__cxx11::basic_string<char> >’:
/usr/include/boost/variant/get.hpp:201:35:   required from ‘typename boost::add_pointer<const U>::type boost::strict_get(const boost::variant<T0, TN ...>*) [with U = std::__cxx11::basic_string<char>; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const std::__cxx11::basic_string<char>*]’
/usr/include/boost/variant/get.hpp:269:25:   required from ‘typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, TN ...>*) [with U = std::__cxx11::basic_string<char>; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const std::__cxx11::basic_string<char>*]’
/home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:291:91:   required from here
/usr/include/boost/variant/detail/element_index.hpp:49:8: error: no type named ‘type’ in ‘struct boost::detail::variant::element_iterator<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const std::__cxx11::basic_string<char> >’
 struct holds_element :
        ^
In file included from /home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:28:0:
/usr/include/boost/variant/get.hpp: In instantiation of ‘typename boost::add_pointer<const U>::type boost::strict_get(const boost::variant<T0, TN ...>*) [with U = std::__cxx11::basic_string<char>; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const std::__cxx11::basic_string<char>*]’:
/usr/include/boost/variant/get.hpp:269:25:   required from ‘typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, TN ...>*) [with U = std::__cxx11::basic_string<char>; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const std::__cxx11::basic_string<char>*]’
/home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:291:91:   required from here
/usr/include/boost/variant/get.hpp:201:35: error: ‘value’ is not a member of ‘boost::detail::variant::holds_element<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const std::__cxx11::basic_string<char> >’
     return relaxed_get<U>(operand);
                                   ^
In file included from /usr/include/boost/variant/get.hpp:24:0,
                 from /home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:28:
/usr/include/boost/variant/detail/element_index.hpp: In instantiation of ‘struct boost::detail::variant::holds_element<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const double>’:
/usr/include/boost/variant/get.hpp:201:35:   required from ‘typename boost::add_pointer<const U>::type boost::strict_get(const boost::variant<T0, TN ...>*) [with U = double; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const double*]’
/usr/include/boost/variant/get.hpp:269:25:   required from ‘typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, TN ...>*) [with U = double; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const double*]’
/home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:301:86:   required from here
/usr/include/boost/variant/detail/element_index.hpp:49:8: error: no type named ‘type’ in ‘struct boost::detail::variant::element_iterator<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const double>’
 struct holds_element :
        ^
In file included from /home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:28:0:
/usr/include/boost/variant/get.hpp: In instantiation of ‘typename boost::add_pointer<const U>::type boost::strict_get(const boost::variant<T0, TN ...>*) [with U = double; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const double*]’:
/usr/include/boost/variant/get.hpp:269:25:   required from ‘typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, TN ...>*) [with U = double; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const double*]’
/home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:301:86:   required from here
/usr/include/boost/variant/get.hpp:201:35: error: ‘value’ is not a member of ‘boost::detail::variant::holds_element<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const double>’
     return relaxed_get<U>(operand);
                                   ^
In file included from /usr/include/boost/variant/get.hpp:24:0,
                 from /home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:28:
/usr/include/boost/variant/detail/element_index.hpp: In instantiation of ‘struct boost::detail::variant::holds_element<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const int>’:
/usr/include/boost/variant/get.hpp:201:35:   required from ‘typename boost::add_pointer<const U>::type boost::strict_get(const boost::variant<T0, TN ...>*) [with U = int; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const int*]’
/usr/include/boost/variant/get.hpp:269:25:   required from ‘typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, TN ...>*) [with U = int; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const int*]’
/home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:311:83:   required from here
/usr/include/boost/variant/detail/element_index.hpp:49:8: error: no type named ‘type’ in ‘struct boost::detail::variant::element_iterator<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const int>’
 struct holds_element :
        ^
In file included from /home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:28:0:
/usr/include/boost/variant/get.hpp: In instantiation of ‘typename boost::add_pointer<const U>::type boost::strict_get(const boost::variant<T0, TN ...>*) [with U = int; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const int*]’:
/usr/include/boost/variant/get.hpp:269:25:   required from ‘typename boost::add_pointer<const U>::type boost::get(const boost::variant<T0, TN ...>*) [with U = int; T0 = std::__cxx11::basic_string<char>; TN = {int, double, bool}; typename boost::add_pointer<const U>::type = const int*]’
/home/oxid/AI/opencog/opencog/opencog/spatial/Entity.cc:311:83:   required from here
/usr/include/boost/variant/get.hpp:201:35: error: ‘value’ is not a member of ‘boost::detail::variant::holds_element<boost::variant<std::__cxx11::basic_string<char>, int, double, bool>, const int>’
     return relaxed_get<U>(operand);
                                   ^
opencog/spatial/CMakeFiles/SpaceMap.dir/build.make:326: recipe for target 'opencog/spatial/CMakeFiles/SpaceMap.dir/Entity.cc.o' failed
make[2]: *** [opencog/spatial/CMakeFiles/SpaceMap.dir/Entity.cc.o] Error 1
CMakeFiles/Makefile2:2970: recipe for target 'opencog/spatial/CMakeFiles/SpaceMap.dir/all' failed
make[1]: *** [opencog/spatial/CMakeFiles/SpaceMap.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2`

The error on pastebin : http://pastebin.com/4ZmxjHyq

Best regards,
Samuel

**Comment by SamuelHassine** [comment]
The error on Pastebin should more readable: http://pastebin.com/ydXLm8zj.

**Comment by linas** [comment]
Hmm, this is a bug in boost, not in opencog. Did you report a boost bug? #2335 is a work-around, but its ultimately just a hack.
