### ISSUE TITLE
build failure LGDictExpContainer.cc after updating link-grammar to 5.4.4

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#3011]
i had to copy `connectors.h`, `api-types.h`, `lg_assert.h`, and `string-set.h` to `/usr/local/include/link-grammar/` and then ran into a bunch of undeclared variables:
````
[ 49%] Building CXX object opencog/nlp/lg-dict/CMakeFiles/lg-dict-entry.dir/LGDictExpContainer.cc.o
In file included from /usr/local/include/link-grammar/memory-pool.h:16:0,
                 from /usr/local/include/link-grammar/connectors.h:24,
                 from /usr/local/include/link-grammar/dict-structures.h:18,
                 from /usr/local/include/link-grammar/dict-api.h:17,
                 from /home/mozi/oc/opencog/opencog/nlp/lg-dict/LGDictExpContainer.h:27,
                 from /home/mozi/oc/opencog/opencog/nlp/lg-dict/LGDictExpContainer.cc:27:
/usr/local/include/link-grammar/utilities.h:166:13: error: conflicting declaration ‘typedef int locale_t’
 typedef int locale_t;
             ^~~~~~~~
In file included from /usr/include/wchar.h:49:0,
                 from /usr/include/c++/7/cwchar:44,
                 from /usr/include/c++/7/bits/postypes.h:40,
                 from /usr/include/c++/7/bits/char_traits.h:40,
                 from /usr/include/c++/7/string:40,
                 from /usr/local/include/opencog/atoms/base/Link.h:27,
                 from /home/mozi/oc/opencog/opencog/nlp/lg-dict/LGDictExpContainer.cc:24:
/usr/include/x86_64-linux-gnu/bits/types/locale_t.h:24:20: note: previous declaration as ‘typedef struct __locale_struct* locale_t’
 typedef __locale_t locale_t;

                    ^~~~~~~~
/home/mozi/oc/opencog/opencog/nlp/lg-dict/LGDictExpContainer.cc: In constructor ‘opencog::LGDictExpContainer::LGDictExpContainer(Exp_type, Exp*)’:
/home/mozi/oc/opencog/opencog/nlp/lg-dict/LGDictExpContainer.cc:53:23: error: ‘union Exp_struct::<unnamed>’ has no member named ‘string’
     m_string = exp->u.string;
                       ^~~~~~
```

**Comment by linas** [comment]
Mike, please stop building link-grammar from github. It is gauranteed to be broken! This is a development version, its incomplete. The release tarballs, by contrast, are vetted, tested, and are supported.

To be clear: link-grammar has a formal release process. Use that, you won't get burned. Other parts of opencog do not yet have a formal release process, so you have no choice except to work from github.  But here, you can avoid the pain.

**Comment by linas** [comment]
Anyway, you now have to remove the contents from `/usr/local/include` by hand, because you have now introduced garbage there that will interfere with future builds.   Copying anything at all, by hand, to /usr/bin, /usr/lib, etc is a dangerous activity, as the manual tweaks are almost always incompatible with future system updates, and leave the system in some undefined, undebuggable state.

I've notice that you frequently struggle with strange errors that others do not experience -- I'm starting to think that this might be because you manually copied files into system directories, or performed manual over-rides of other sorts. You really want to avoid that.

**Comment by mhatta** [comment]
I stumbled upon the same problem and kind of figured out what's going on.

1) Several header files are not installed under /usr/include/link-grammar if you build link-grammar 5.4.4 using the old Debian packaging files (debian/ from 5.3.16-2?).  Thus, liblink-grammar-dev doesn't contain those files.

Missing headers seems to be : api-types.h, connectors.h, lg_assert.h, memory-pool.h, strings-set.h, utilities.h

Those are included from other installed headers files in /usr/include/link-grammar anyway (e.g. dict-structures.h calls the missing connectors.h), so it breaks the build of opencog.

I'm not sure whether those headers are installed if you build link-grammar by hand.

2) LGDictExpContainer.cc of opencog and utilities.h of link-grammar have conflicting definition

If you somehow install those missing headers into /usr/include/link-grammar by hand, then there is conflicting definition.

/usr/include/link-grammar/utlities.h: typedef int locale_t;
opencog/nlp/lg-dict/LGDictExpContainer.cc: typedef __locale_t locale_t;

So e.g. changing int to __locale_t in utilities.h fixes the build, but I'm not sure this is the right way.

**Comment by linas** [comment]
Hi @mhatta Please use version 5.4.3 or earlier, for now. There's a mistake in 5.4.4.  that will be fixed real soon now.

**Comment by linas** [comment]
Closing; this is fixed by version 5.5.0, released just now.  Using version 5.4.4 will generate a permanent error; version 5.4.3 and earlier should work.

**Comment by linas** [comment]
Sorry for the delay. Lots of things going on.
