### ISSUE TITLE
libiberty not found on Ubuntu 14.04

### ISSUE THREAD

**Issue by edajade** [opencog/opencog#696]
[  1%] Building C object opencog/util/CMakeFiles/cogutil.dir/backtrace-symbols.c.o
/home/jade/src/opencog/opencog/util/backtrace-symbols.c:65:23: fatal error: libiberty.h: No such file or directory

libiberty-dev contains /usr/include/libiberty/libiberty.h
but this isn't found by the build system (because it's in the wrong directory)

Only got this error after upgrading from 12.04 to 14.04
